#!/bin/bash
# author: lucas

# ================ User Setup ====================

if [[ $(git config --global user.email) = '' ]]; then
  echo "Getting user information before setup:"
  echo "Enter full name:"
  read name
  echo "Enter email for Git:"
  read email
fi

# ================ Terminal Configuration ====================

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then

  # Homebrew
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing Homebrew..."
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Installing brews and casks..."
    brew bundle --global
  fi

fi

echo "Configuring Git..."
git config --global user.name $name > /dev/null 2>&1
git config --global user.email $email > /dev/null 2>&1
gh auth login

# Zsh
echo "Installing zsh4humans..."
if command -v curl >/dev/null 2>&1; then
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/romkatv/zsh4humans/v5/install)"
else
  sh -c "$(wget -O- https://raw.githubusercontent.com/romkatv/zsh4humans/v5/install)"
fi

if [[ "$SHELL" != "/bin/zsh" ]]; then
  echo "Setting ZSH as default shell..."
  chsh -s /bin/zsh
  compaudit | xargs chmod g-w
fi

# Tmux
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
  
# macOS
echo "Tweaking macOS defaults..."
source ~/.macos

# ================ Languages ====================

# Rust
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

# ================ Theming ====================

# Fonts

# iTerm
# TODO: link iterm profile
